 version: "3"
 services:
  web_service:
    build:
      context: ./
      dockerfile: ./dockerfiles/Dockerfile
    image: workshop1_web
    container_name: workshop_web_container
    stdin_open: true #  docker attach container_id
    tty: true
    ports:
     - "8000:8000"
    volumes:
     - .:/root/workspace/site
